name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.17.0"

      - name: Install
        run: yarn install

      - name: Switch to Node 8 for Gitbook CLI
        uses: actions/setup-node@v1
        with:
          node-version: "8.17.0"

      - name: Build Gitbook
        run: yarn build

      - name: Switch Back to Node 16
        uses: actions/setup-node@v1
        with:
          node-version: "16.17.0"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _book
          branch: gh-pages
