name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.17.0"

      - name: Install
        run: yarn install

      - name: Switch to Node 8 for Gitbook CLI
        uses: actions/setup-node@v1
        with:
          node-version: "8.17.0"

      - name: Build Gitbook
        run: yarn build

      - name: Switch Back to Node 16
        uses: actions/setup-node@v1
        with:
          node-version: "16.17.0"

      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: _book
      #     branch: gh-pages

      - name: Init new repo in _book folder and commit generated files
        run: |
          cd _book
          git init
          git add -A
          git config --global --add safe.directory /github/workspace/_book
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./_book
